### ISSUE TITLE
Insert failed

### ISSUE THREAD

**Issue by Andy-AO** [Gruntfuggly/auto-snippet#10]
Can see the inserted information on the OutPut, but it didn't succeed.

The Snippet I want to insert is called re.

![image](https://user-images.githubusercontent.com/38101170/110743605-4119ec80-8273-11eb-96e6-378c04d0b27a.png)

![image](https://user-images.githubusercontent.com/38101170/110743624-4b3beb00-8273-11eb-8695-6fc6377a2ff7.png)

**Comment by Gruntfuggly** [comment]
Please can you post your snippets file and your settings so I can try to recreate it?

**Comment by Andy-AO** [comment]
> Please can you post your snippets file and your settings so I can try to recreate it?

I'm sorry, but there was a mistake in my configuration.

I confused 'snippet name' with 'prefix',so `re` doesn't really exist.

It took me a long time to realize this.

sorry.

If there is a reminder in the output information when it cannot be found, it will be better.

**Comment by Gruntfuggly** [comment]
Unfortunately there is no real API for inserting the snippets - it just has to try. There is a timer which tries to check if something happened, but it probably doesn't work in all cases.

**Comment by Gruntfuggly** [comment]
I've just pushed an update which also tests to see if the file is empty after the insertion.

**Comment by chrisbward** [comment]
Also had the same issue until I switched prefix for name. This wasn't immediately obvious.
