### ISSUE TITLE
Exclude .git from pattern

### ISSUE THREAD

**Issue by matronator** [Gruntfuggly/auto-snippet#11]
If I use pattern `**/*.php`, every time I open a diff preview of a modified PHP file, the extension tries to insert the snippet, breaking the diff window and making it impossible to preview changes of all PHP files. Also sometimes it inserts the snippet after opening an existing file that hasn't been committed yet.

**Comment by Gruntfuggly** [comment]
Does it work if you use `"language":"php"` instead of the pattern?

**Comment by matronator** [comment]
If I use that, it doesn't work at all, as per #9 (even with the html workaround)

**Comment by Gruntfuggly** [comment]
OK. I'll see if I can find a way to ignore diff files, etc.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which should only trigger on documents with a "file" scheme, so hopefully it will work better. Can you let me know if it works for you?
