### ISSUE TITLE
Specify pattern documentation

### ISSUE THREAD

**Issue by hyoretsu** [Gruntfuggly/auto-snippet#12]
I was just about to create a bug issue because pattern matching wasn't working. But the problem was that you **have** to place `**/` at the beginning of every pattern. That was never mentioned in the README.

**Comment by Gruntfuggly** [comment]
You don't have to use it - it just matches any folder (it's a glob pattern) and it is shown in the examples.

I agree that it might not be familiar if a user hasn't come across globs before, so I'll add something to make it clearer.

**Comment by Gruntfuggly** [comment]
I've added some more detail in the README.md in the latest version.
