### ISSUE TITLE
Consider using RegEx

### ISSUE THREAD

**Issue by hyoretsu** [Gruntfuggly/auto-snippet#13]
RegEx'd be better imo. It's used way more frequently and it's also better documented than however many glob patterns there are in micromatch.

**Comment by Gruntfuggly** [comment]
A regex for matching a file in any folder (or subfolder) would be more complicated than `**/*`, although I suppose it could be as simple as `.*\.js` for example.

I'll add it as an option.

**Comment by Gruntfuggly** [comment]
Latest version now has an option to match on regex.
