### ISSUE TITLE
Path not matching as expected

### ISSUE THREAD

**Issue by chrisbward** [Gruntfuggly/auto-snippet#14]
Hi! Great tool, just setting up...

```
"autoSnippet.snippets": [
        { "pattern": "frontend/**/*.tsx", "snippet": "My Component Example },
      ], 
```

Is my glob causing the issue here? I would expect it to match files within the path, nested.

**Comment by Gruntfuggly** [comment]
The globs are absolute, so you probably want `**/frontend/**/*.tx`

**Comment by chrisbward** [comment]
That was exactly my issue and you beat me to it :))

Well done, tool is bloody brilliant!

**Comment by Gruntfuggly** [comment]
Glad you're finding it useful! 🙂
