### ISSUE TITLE
[Help Wanted] Execute different snippet for similar file extension .tsx and .stories.tsx

### ISSUE THREAD

**Issue by RodrigoTomeES** [Gruntfuggly/auto-snippet#18]
Hi,

First of all thanks for your work. I want to execute the snippet story in stories.tsx and the snippet functional-component in tsx but always is executed the tsx snippet. I've tried using regex instead of pattern but haven't been able to get it to work with subfolders.

This is my configuration:

```json
{
  "autoSnippet.snippets": [
    { "pattern": "**/components/**/*.tsx", "snippet": "functional-component" },
    { "pattern": "**/components/**/*.stories.tsx", "snippet": "story" },
    { "pattern": "**/components/**/index.ts", "snippet": "index" },
    { "pattern": "**/components/**/types.ts", "snippet": "type" }
    //{ "regex": ".\\/*.tsx", "snippet": "story" }
  ]
}
```

Thanks!

**Comment by JVApen** [comment]
I've just did a similar setup.
What is important is that it matches from top to bottom.
So by reordering and putting the most restrictive on top (aka *.stories.tsx), it should work.

**Comment by RodrigoTomeES** [comment]
@JVApen yes, you are right, I fixed it some time ago I forget to add here the solution
