### ISSUE TITLE
[suggestion] use languageId instead of file extension

### ISSUE THREAD

**Issue by ctf0** [Gruntfuggly/auto-snippet#2]
which would make it easier for the extension to differentiate between `.php` & `.blade.php`

**Comment by ctf0** [comment]
btw the usage of `"pattern": "*.js",` is not really needed because its already handled by the package https://github.com/Gruntfuggly/auto-snippet/blob/78db4957e30da3bcd8689a8a68cd6814b16f310d/extension.js#L15

so really it should be just `{ "pattern": "js", "snippet": "template" }`

**Comment by Gruntfuggly** [comment]
Unfortunately, I use the extension for C++ work which uses different headers for `.h` and `.cpp` files which are both considered the same language.

I'll see if I can make it an alternative option though.

**Comment by ctf0** [comment]
okay, maybe the pattern key could become an object of either a languageId or an extension

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which can also use the language ID - see the README.md for an example.

**Comment by ctf0** [comment]
thanx for the new update
