### ISSUE TITLE
use snippets without prefix

### ISSUE THREAD

**Issue by ctf0** [Gruntfuggly/auto-snippet#3]
is that possible, the benefit is that it doesnt show up in the auto complete

**Comment by Gruntfuggly** [comment]
How do you mean? Use snippets which don't have a prefix defined?

**Comment by ctf0** [comment]
yes, is it even possible ?

**Comment by Gruntfuggly** [comment]
The extension selects the snippet based on it's name, so it should work, but it seems that snippets with an empty prefix or no prefix at all aren't valid. It did let me set the prefix to a space though - does that help? Which auto complete do you see it in? If you mean the drop down from the "Insert Snippet" command, then it seems to still show it.

**Comment by ctf0** [comment]
the autocomplete i meant is when u type or press `ctrl+space` for example i have a snippet call `php-basic-template` which do show up if u typed `php`

**Comment by Gruntfuggly** [comment]
OK. Even setting the prefix to " ", it still shows up in the auto-complete, so I don't think there is any way around it.

**Comment by ctf0** [comment]
okay np, thank you for ur time & patience :trophy:
