### ISSUE TITLE
not working on windows 10

### ISSUE THREAD

**Issue by Virgilio-AI** [Gruntfuggly/auto-snippet#7]
hello there, I tried to make it work but no matter what I do even leavinf the default configuration it always leaves to an errror 
![Screenshot_1](https://user-images.githubusercontent.com/59902976/94387729-9f617180-0110-11eb-882f-aaf5832faf91.png)
and this is how I have it on my settings.json
![image](https://user-images.githubusercontent.com/59902976/94388331-56122180-0112-11eb-9e80-9d7df53e1b5c.png)
as you can see just the default settings that are given

**Comment by Gruntfuggly** [comment]
Silly question, but have you defined the snippets? Can you post them too?

**Comment by Decipher** [comment]
I'm also unable to get this working with Windows 10, using WSL2, with the same error.

I have created custom snippets and downloading other extensions that provide snippets, confirmed the snippets work when invoked manually, but still get the same error when trying to use the snippet via this extension.

**Comment by Decipher** [comment]
Actually, I retract that. I had incorrectly named the snippet, everything appears to work as expected for me.

**Comment by Gruntfuggly** [comment]
@Virgilio-AI Did you get it working?

**Comment by Virgilio-AI** [comment]
@Gruntfuggly sorry for don't answering your first question but I didn't got an email of an answer untill now,
mm what do you mean by defining the snippets? I mean they are defined already aren't they?.
and @Decipher  can you help me in how do you configure it or how do you have your settings.json

**Comment by Gruntfuggly** [comment]
The extension doesn't define any of its own snippets. What were you expecting them to contain?

**Comment by Virgilio-AI** [comment]
Gruntfuggly all right I get it now it works, I literally expected to print "heade-template", sorry for my lack of experience haha

**Comment by Gruntfuggly** [comment]
Lol - OK, you can make it do that if you want!

Do you think it needs to be made clearer in the README.md? I'm open to suggestions.

Is it OK to close this now?

**Comment by Virgilio-AI** [comment]
I guess for people like me ,your extension is pretty good actually. I guess it would not be harming to put that you have to create a global snippets file and say that in settings.json you are only calling an existing snippet, anyway thanks for answering best wishes to you!
