### ISSUE TITLE
Inserts snippet on every file move

### ISSUE THREAD

**Issue by prk3** [Gruntfuggly/auto-snippet#8]
Hey. Big thanks for working on this addon. It's one of the first plugins I add to a fresh vscode setup.

I noticed a small bug. When you move a new file between folders, a snippet is inserted multiple times. Here is a screen capture.
![Peek 2020-09-30 16-25](https://user-images.githubusercontent.com/16927151/94698551-b8993680-0339-11eb-9999-a426912f16c3.gif)

vscode version: 1.49.2
auto-snippet version: 0.0.8
config:
```
"autoSnippet.snippets": [
        {
            "pattern": "**/*.rs",
            "snippet": "test-snippet"
        },
    ],
```
```
"test-snippet": {
		"prefix": "test-snippet",
		"body": [
			"Some text",
			""
		],
		"description": "test-snippet"
	}
```

**Comment by Gruntfuggly** [comment]
It should probably check if the editor is empty before inserting. I'll take a look.

**Comment by Gruntfuggly** [comment]
OK, I've reproduced this - it seems to only happen if the new file hasn't been saved. It does already check that the file is empty, but it seems that until the file is saved, it appears to still be empty.

I'll carry on investigating...

**Comment by Gruntfuggly** [comment]
I've found a hack which seems to fix it - selecting any text before inserting the snippet works. I'm just checking there are no side effects...

**Comment by Gruntfuggly** [comment]
OK - I've uploaded a new version - let me know if it works OK.

**Comment by prk3** [comment]
Seems like the bug gone. You can see how the text is selected for a fraction of a second. Thanks a lot!
